### ISSUE TITLE
Few cleanups to be done

### ISSUE THREAD

**Issue by knightcube** [2d-inc/HistoryOfEverything#42]
- [ ] Updating flare dependency in pubspec.yaml
- [ ] Updating nima dependency in pubspec.yaml
- [ ] Updating all int values to double to prevent this error -> `error: The argument type 'int' can't be assigned to the parameter type 'double'.`
- [ ] Adding import Future to prevent this error -> `error: Undefined class 'Future'. (undefined_class at [timeline] lib\main_menu\menu_data.dart:86)`

**Comment by luigi-rosso** [comment]
Could you post your pubspec.yaml? Did you modify it? You shouldn't need to do that.

Make sure you initialize and update submodules after cloning this repository. I just tried running the steps in the readme (on the latest version of flutter) and I'm not seeing any of the errors you've listed.

**Comment by knightcube** [comment]
```
name: timeline
description: Flutter Launch Demo

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+17

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nima:
    path: ../dependencies/Nima-Flutter
  flare:
    path: ../dependencies/Flare-Flutter
  flutter_markdown: ^0.2.0
  share: ^0.5.3
  intl: ">=0.14.0"
  shared_preferences: ^0.4.3
  rxdart: ^0.19.0
  url_launcher: ^4.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/Articles/
    - assets/Big_Bang/
    - assets/Milky Way/
    - assets/Mammals/
    - assets/Dinosaurs/
    - assets/Insects/
    - assets/Fish_and_Stuff/
    - assets/Cells/
    - assets/Dinosaur_Demise/
    - assets/Reptiles/
    - assets/World_War_I/
    - assets/Moon/
    - assets/Newton/
    - assets/Cold_war/
    - assets/Crusades/
    - assets/Homo_Sapiens_Sapiens/
    - assets/Nelson Mandela_v2/
    - assets/Martin Luther king/
    - assets/Sufraggette_movement/
    - assets/Marie_Curie/
    - assets/Amelia_Earhart/
    - assets/Alan_Turing/
    - assets/World_War_II/
    - assets/Darwin 2/
    - assets/Internet/
    - assets/Agricultural_evolution/
    - assets/Writing/
    - assets/Recorded_history/
    - assets/Pyramid/
    - assets/Roma/
    - assets/Industrialization/
    - assets/Constantinople/
    - assets/BlackPlague/
    - assets/First_Temple/
    - assets/Apes/
    - assets/Constructive_Tools/
    - assets/Fire/
    # - assets/search_icon.png
    # - assets/flutter_logo.png
    # - assets/right_arrow.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```
